-record('bson.objectid', {value}).
-record('bson.timestamp', {value}).
-record('bson.javascript', {value}).
-record('bson.regexp', {value}).
-record('bson.binary', {type, value}).
-record('bson.long', {value}).
